// src/constants/theme.js

const colors = {
    secondary: {
      light: '#e6f6f4',
      lightHover: '#d9f2ef',
      lightActive: '#b0e4dd',
      normal: '#00a991',
      normalHover: '#009883',
      normalActive: '#008774',
      dark: '#007f6d',
      darkHover: '#006557',
      darkActive: '#004c41',
      darker: '#003b33',
    },
    primary: {
      light: '#e6edef',
      lightHover: '#d9e4e7',
      lightActive: '#b0c7cd',
      normal: '#00495f',
      normalHover: '#004256',
      normalActive: '#003a4c',
      dark: '#003747',
      darkHover: '#002c39',
      darkActive: '#00212b',
      darker: '#001a21',
    },
    base: {
      light: '#fdfdfd',
      lightHover: '#fdfdfd',
      lightActive: '#fafafa',
      normal: '#efefef',
      normalHover: '#d7d7d7',
      normalActive: '#bfbfbf',
      dark: '#b3b3b3',
      darkHover: '#8f8f8f',
      darkActive: '#6c6c6c',
      darker: '#545454',
    },
    dark: {
      light: '#f3f3f3',
      lightHover: '#ededed',
      lightActive: '#dadada',
      normal: '#888888',
      normalHover: '#7a7a7a',
      normalActive: '#6d6d6d',
      dark: '#666666',
      darkHover: '#525252',
      darkActive: '#3d3d3d',
      darker: '#303030',
    }
  };
  
  const typography = {
    Poppins: {
      boldH1: {
        fontFamily: 'Poppins',
        fontSize: 42,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldH2: {
        fontFamily: 'Poppins',
        fontSize: 35,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldH3: {
        fontFamily: 'Poppins',
        fontSize: 29,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldH4: {
        fontFamily: 'Poppins',
        fontSize: 24,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldH5: {
        fontFamily: 'Poppins',
        fontSize: 20,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldH6: {
        fontFamily: 'Poppins',
        fontSize: 17,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldBody: {
        fontFamily: 'Poppins',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldCaption1: {
        fontFamily: 'Poppins',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldCaption2: {
        fontFamily: 'Poppins',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
      boldCaption3: {
        fontFamily: 'Poppins',
        fontSize: 8,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '120%',
      },
    },
    Quicksand: {
      h1: {
        fontFamily: 'Quicksand',
        fontSize: 42,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      h2: {
        fontFamily: 'Quicksand',
        fontSize: 35,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      h3: {
        fontFamily: 'Quicksand',
        fontSize: 29,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      h4: {
        fontFamily: 'Quicksand',
        fontSize: 24,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      h5: {
        fontFamily: 'Quicksand',
        fontSize: 20,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      h6: {
        fontFamily: 'Quicksand',
        fontSize: 17,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      body: {
        fontFamily: 'Quicksand',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      caption1: {
        fontFamily: 'Quicksand',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      caption2: {
        fontFamily: 'Quicksand',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
      caption3: {
        fontFamily: 'Quicksand',
        fontSize: 8,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '120%',
      },
    },
  };
  
  export { colors, typography };
  